### ISSUE TITLE
NR4. Response Time

### ISSUE THREAD

**Issue by WilliamVoker** [WSU-4110/tule#1]
|NR4.  Response Time|
|---|
|**Goal**: The application should take no longer than 2 seconds to respond.
**Stakeholders:**  Project Team, Customers, Instructor|
|**Description**: When the user enters in their data i.e  signing up, logging into their account or even asking for their saved information to be displayed, the application should complete this user request in at most 2 seconds. |
|**Origin:** Requirements Meeting 1|
|**Version:** 1.0  |
|**Date:** 01/30/2023
|  **Priority:** Low |

**Comment by bhodgins3** [comment]
login and full database query for all tasks is satisfying this. I would say complete
