### ISSUE TITLE
FR1. Add Task to a List

### ISSUE THREAD

**Issue by fatcatsnrats** [WSU-4110/tule#14]
| FR1. Add Task to a List|
|---|
|**Goal**: The user should be able to add a task to their task list.
**Stakeholders:** Project Team, Customers, Instructor |
| **Description:** User will have a task list that they can add tasks with certain attributes to. All active tasks are stored in the task list. |
| **Origin:** Project proposal meeting |
| **Version:** 1.0  |  
|**Date:** 02/01/2023  
|  **Priority:** High |

**Comment by bhodgins3** [comment]
Essentially complete, New task data is stored to the backend.
