### ISSUE TITLE
NR1. Hidden Passwords

### ISSUE THREAD

**Issue by fatcatsnrats** [WSU-4110/tule#15]
| NR1. Hidden Passwords|
|---|
|**Goal**: Passwords will be hidden while being entered.
**Stakeholders:** Project Team, Customers, Instructor |
| **Description:** The text inputted in the password field on the login and sign-up page will be obfuscated with asterisks. |
| **Origin:** Project proposal meeting |
| **Version:** 1.0  |  
|**Date:** 02/01/2023  
|  **Priority:** Medium |

**Comment by bhodgins3** [comment]
Complete
