### ISSUE TITLE
FR5. Breaks

### ISSUE THREAD

**Issue by fatcatsnrats** [WSU-4110/tule#19]
| FR5. Breaks  |
|---|
|**Goal**: The user can set break times after tasks. 
**Stakeholders:** Project Team, Customers, Instructor |
| **Description:** When the user is creating a task, they can specify if the task should have a break after it and for how long the break should last. |
| **Origin:** Project proposal meeting |
| **Version:** 1.0  |  
|**Date:** 02/01/2023  
|  **Priority:** Medium |

**Comment by bhodgins3** [comment]
Complete
