### ISSUE TITLE
FR16. Login and Account Creation

### ISSUE THREAD

**Issue by WilliamVoker** [WSU-4110/tule#2]
|FR16.   Login and Create Account|
|---|
|**Goal**: The User Should be able to create and login to their own account.
**Stakeholders:** Project Team, Customers, Instructor|
| **Description:** When the user opens the application, they should be given the option to sign up so that they can have an account that allows their information to be saved. When they come back to the application they should be able to login to their account to access their tasks and schedules.|
| **Origin:** Requirement meeting 1|
| **Version:** 1.0  |
|**Date:** 02/01/2023
|  **Priority:** High |

**Comment by bhodgins3** [comment]
Complete
