### ISSUE TITLE
FR11. Task Editing

### ISSUE THREAD

**Issue by Oskar-Schermerhorn** [WSU-4110/tule#20]
|FR11 Task Editing|
|---|
|**Goal**: The user should be able to edit the attributes of any tasks in their task list
**Stakeholders:** Project Team, Customers, Instructor.|
| **Description:** When a user is viewing their schedule or task list they would be able to select a task. Once the task is selected, the application would display the attributes associated with that task. From this point, the user would be able to select any of the existing attributes and change them to their liking. The user would also be able to add any optional attributes that were not previously included.|
| **Origin:** Project proposal meeting|
| **Version:** 1.0  |
|**Date:** 1/23/23
|  **Priority:** Medium|

**Comment by bhodgins3** [comment]
Task editing was very close to completion. The functionality was there, reading from the back end was complete, but the fetch request was failing. Didn't have time to address this.
