### ISSUE TITLE
FR12. Task Priority

### ISSUE THREAD

**Issue by Oskar-Schermerhorn** [WSU-4110/tule#21]
|FR12. Task Priority|
|---|
|**Goal**: The user should be able to set a priority level of a task
**Stakeholders:** Project Team, Customers, Instructor.|
| **Description:** When creating or editing a task, the user should be able to select which tasks are more important, relative to other tasks. The application would allow the user to choose between options to describe the tasks priority. |
| **Origin:** Project proposal meeting |
| **Version:** 1.0  |
|**Date:** 1/23/23
|  **Priority:** High |

**Comment by bhodgins3** [comment]
Completed by Oskar
