### ISSUE TITLE
FR13. Task Times

### ISSUE THREAD

**Issue by Oskar-Schermerhorn** [WSU-4110/tule#22]
|FR13. Task Times|
|---|
|**Goal**: The user should be able to set a duration and an optional start time for a task
**Stakeholders:** Project Team, Customers, Instructor.|
| **Description:** When creating a task, users will specify the duration of that task. They can also specify a start time for a task. This feature would be for particularly time sensitive tasks such as going to a class at a specified time.  |
| **Origin:** Project proposal meeting |
| **Version:** 1.0  |
|**Date:** 1/23/23
|  **Priority:** High |

**Comment by bhodgins3** [comment]
This is logged into backend, just needs to be called
