### ISSUE TITLE
FR14. Recurrence

### ISSUE THREAD

**Issue by Oskar-Schermerhorn** [WSU-4110/tule#23]
|FR14. Recurrence|
|---|
|**Goal**: The user should be able to set a task to be repeated
**Stakeholders:** Project Team, Customers, Instructor.|
| **Description:** When creating a task, the user would be able to determine whether a task should be repeated. This, when selected, would cause the task to be added to the user’s task list every day or specific days of the week depending on the user’s preference. When a task is repeated using this feature, all of the selected attributes of the task, such as the start time or priority, will be the same as when the task was initially added. |
| **Origin:** Project Proposal Meeting|
| **Version:** 1.0  |
|**Date:** 1/23/23
|  **Priority:** Medium |

**Comment by bhodgins3** [comment]
There were issues with the back end, and the algorithm that took higher priority than this.
