### ISSUE TITLE
NR3. Privacy

### ISSUE THREAD

**Issue by Oskar-Schermerhorn** [WSU-4110/tule#25]
|NR3. Privacy|
|---|
|**Goal**: Our system shall not share a users schedule or task list without notifying the user
**Stakeholders:** Project Team, Customers, Instructor.|
| **Description:** When the user creates a task list or schedule, the application will not allow other users to see their schedule, names of the tasks, or any other attribute of the tasks. |
| **Origin:** Requirements meeting 1|
| **Version:** 1.0  |
|**Date:** 1/30/23
|  **Priority:** Low |

**Comment by bhodgins3** [comment]
Should be difficult to do this at this point.
