### ISSUE TITLE
Weekly Planner Display

### ISSUE THREAD

**Issue by maazooshake** [WSU-4110/tule#28]
|FR1.  Weekly Planner Display|
|---|
|**Goal**: The app can display the user’s schedule in a weekly form. 
**Stakeholders:** Project Team, Customers, Instructor|
| **Description:** The application, in addition to displaying the user’s schedule on a daily basis, can also display the user’s schedule on a weekly basis. It can show all the days at the same time as well, and the tasks corresponding to the times on each day.|
| **Origin:** Project Proposal Meeting|
| **Version:** 1.0  |
|**Date:** 1/23/23
|  **Priority:** High|

**Comment by bhodgins3** [comment]
There were layout changes and other things that didn't go as planned with the daily planner that made it difficult to implement this feature.
