### ISSUE TITLE
Task Progress Tracker

### ISSUE THREAD

**Issue by maazooshake** [WSU-4110/tule#29]
|FR1.  Task Progress Tracker|
|---|
|**Goal**:App can track the user’s progress of completing all their designated tasks, and display it on the homepage.
**Stakeholders:** Project Team, Customers, Instructor|
| **Description:**  The application will keep track of the user’s completion of their tasks relative to all the tasks they have on their schedule. The app will display this on the homepage as a circle that’s filled relative to how much the user has completed i.e. half the tasks being finished means the circle will be half full  |
| **Origin:**Requirements Meeting 1|
| **Version:** 1.0  |
|**Date:** 1/30/23
|  **Priority:** Medium |

**Comment by WilliamVoker** [comment]
Done
