### ISSUE TITLE
FR17. Schedule Editing

### ISSUE THREAD

**Issue by WilliamVoker** [WSU-4110/tule#3]
|FR17.  Schedule Editing|
|---|
|**Goal**: The user should be able to edit their schedule.
**Stakeholders:**Project Team, Customers, Instructor|
| **Description:** After the user’s schedule has been generated, a user should be able to go back into the application so that they can change the order of tasks, whether or not they want the task done that day so that they are not confined to the schedule generated by the application based on the initial tasks and task properties they provided. |
| **Origin:** Project Proposal meeting |
| **Version:** 1.0  |
|**Date:** 01/23/2023
|  **Priority:** Medium |

**Comment by bhodgins3** [comment]
This was dependent on altTask functionality.
