### ISSUE TITLE
Web Application

### ISSUE THREAD

**Issue by maazooshake** [WSU-4110/tule#31]
|FR1.  Web Application|
|---|
|**Goal**:  Implement the application as a website app
**Stakeholders:** Project Team, Customers, Instructor|
| **Description:** As opposed to a phone application, Tule will specifically be a website app.   |
| **Origin:** Project Proposal Meeting|
| **Version:** 1.0  |
|**Date:** 1/23/23
|  **Priority:** High |

**Comment by bhodgins3** [comment]
This is done
