### ISSUE TITLE
FR18. Task Completion

### ISSUE THREAD

**Issue by WilliamVoker** [WSU-4110/tule#4]
|FR18.  Task Completion|
|---|
|**Goal**: The user should be able to tell application when they have completed a task.
**Stakeholders:** Project Team, Customers, Instructor.|
| **Description:** If the duration of time a user has designated for a task is over, then the user can let the application know that they have completed the task. In addition, if the user completes a task early then they should be able to let the application know so that their schedule can be updated. |
| **Origin:** Requirements meeting 1 |
| **Version:** 1.0  |
|**Date:** 01/30/2023
|  **Priority:** High |

**Comment by bhodgins3** [comment]
Pretty much complete, just ran into time constraints on implementation. Fetch request was failing.
