### ISSUE TITLE
FR19. Unfinished Tasks

### ISSUE THREAD

**Issue by WilliamVoker** [WSU-4110/tule#5]
|FR19.  Unfinished Tasks|
|---|
|**Goal**: The user should be able to tell application when they have not completed a task.
**Stakeholders:** Project Team, Customers, Instructor|
| **Description:** If the duration of time a user has designated for a task is over, but the user has not yet completed the task, then the user should be able to tell the application that the task is not completed and be given the option to add more time to that task. |
| **Origin:** Project Proposal Meeting |
| **Version:** 1.0  |
|**Date:** 01/23/2023
|  **Priority:** High |

**Comment by bhodgins3** [comment]
Implementation was completed on the backend, but the whole app wasn't to a point that we could use it given the time constraints.
