### ISSUE TITLE
FR20. Alternative Tasks

### ISSUE THREAD

**Issue by WilliamVoker** [WSU-4110/tule#6]
|FR20.  Alternative tasks|
|---|
|**Goal**: The user should be able to select alternative tasks in place of another task.
**Stakeholders:** Project Team, Customers, Instructor|
| **Description:** If a user has a long list of tasks that can’t fit into the allotted time in the day, then the user should have the option to select an alternative task amongst the tasks that were not included in the schedule that day to replace a task that is in the generated schedule. |
| **Origin:** Requirements Meeting 1|
| **Version:** 1.0  |
|**Date:** 01/30/2023
|  **Priority:** Low |

**Comment by bhodgins3** [comment]
Functionality was there on the backend, but main algorithm implementation took priority.
