### ISSUE TITLE
NR5. Location Privacy

### ISSUE THREAD

**Issue by WilliamVoker** [WSU-4110/tule#7]
|NR5.  Location Privacy|
|---|
|**Goal**: The application should never access the user’s location without their permission.
**Stakeholders:** Project Team, Customers, Instructor|
| **Description:** The application will accomplish this without using location data. |
| **Origin:** Requirements Meeting 1 |
| **Version:** 1.0  |
|**Date:** 01/30/2023
|  **Priority:** Low |

**Comment by bhodgins3** [comment]
Inherent to the app
